name: Build and Deploy Java App to Azure

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build JAR with Maven
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5️⃣ Deploy JAR directly
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: obter-calendario
          package: target/obter-calendario-0.0.1-SNAPSHOT.jar
