name: Build and Deploy Spring Boot JAR to Azure

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build the JAR
      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      # 4️⃣ Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5️⃣ Deploy JAR directly to Azure Web App
      - name: Deploy JAR to Azure Web App
        run: |
          az webapp deploy \
            --resource-group rg-lab \
            --name obter-calendario \
            --src-path target/obter-calendario-0.0.1-SNAPSHOT.jar \
            --type jar \
            --restart true

      # 6️⃣ (Optional) Stream logs to check deployment
      - name: Tail Azure Web App logs
        run: az webapp log tail --name obter-calendario --resource-group rg-lab
