name: Build, Analyze (Quality Gate), and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-analyze-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Cache Maven packages for speed
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 3) Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4) Build the JAR
      - name: Build JAR with Maven
        run: mvn -B -DskipTests package

      # 5) Run SonarCloud scan and wait for Quality Gate
      - name: SonarCloud scan with Quality Gate
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .   # root of the project where pom.xml / sonar-project.properties lives
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # GitHub token (auto-generated)
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # SonarCloud token
          # Optional if you don't have sonar-project.properties:
          # SONAR_ORG: ${{ secrets.SONAR_ORG }}
          # SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          # SONAR_HOST_URL: https://sonarcloud.io

      # 6) Azure login (runs only if SonarCloud Quality Gate passed)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7) Deploy JAR to Azure Web App
      - name: Deploy JAR to Azure Web App
        run: |
          az webapp deploy \
            --resource-group rg-lab \
            --name obter-calendario \
            --type jar \
            --src-path target/obter-calendario-0.0.1-SNAPSHOT.jar
