name: Build and Deploy Docker to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build JAR
      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      # 4️⃣ Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t obter-calendario:latest .

      # 6️⃣ Push Docker image to Azure Web App
      - name: Deploy Docker container to Azure Web App
        run: |
          az webapp create \
            --resource-group rg-lab \
            --plan obter-calendario-plan \
            --name obter-calendario \
            --deployment-container-image-name obter-calendario:latest || echo "App already exists"
          
          az webapp config container set \
            --name obter-calendario \
            --resource-group rg-lab \
            --docker-custom-image-name obter-calendario:latest